Microwave.Web/Models/ErrorViewModel.cs
using System;

namespace Microwave.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Microwave.Web/Controllers/MicrowaveController.cs
using Microsoft.AspNetCore.Mvc;
using Microwave.Web.Models;
using System.Diagnostics;

namespace Microwave.Web.Controllers
{
    public class MicrowaveController : Controller
    {
        public IActionResult Index()
        {
            var state = Microwave.Api.GetState();
            ViewData["State"] = Microwave.Api.StateToString(state);
            ViewData["ErrorMessage"] = "";
            return View("Index");
        }

        public IActionResult Start(int howLong)
        {
            var result = Microwave.Api.Start(howLong);
            ViewData["State"] = Microwave.Api.StateToString(result.State);
            ViewData["ErrorMessage"] = Microwave.Api.ErrorToString("en-GB", result.Error);
            return View("Index");
        }


        public IActionResult Open()
        {
            var result = Microwave.Api.Open();
            ViewData["State"] = Microwave.Api.StateToString(result.State);
            ViewData["ErrorMessage"] = Microwave.Api.ErrorToString("en-GB", result.Error);
            return View("Index");
        }

        public IActionResult Close()
        {
            var result = Microwave.Api.Close();
            ViewData["State"] = Microwave.Api.StateToString(result.State);
            ViewData["ErrorMessage"] = Microwave.Api.ErrorToString("en-GB", result.Error);
            return View("Index");
        }

        public IActionResult Stop()
        {
            var result = Microwave.Api.Stop();
            ViewData["State"] = Microwave.Api.StateToString(result.State);
            ViewData["ErrorMessage"] = Microwave.Api.ErrorToString("en-GB", result.Error);
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Microwave.Web/Views/Microwave/Index.cshtml
<h1>Microwave</h1>

<form asp-controller="Microwave" asp-action="Start" method="post">
    <input type="number" name="HowLong">
    <button>Start</button>
</form>

<form asp-controller="Microwave" asp-action="Open" method="post">
    <button>Open</button>
</form>
<form asp-controller="Microwave" asp-action="Close" method="post">
    <button>Close</button>
</form>
<form asp-controller="Microwave" asp-action="Stop" method="post">
    <button>Stop</button>
</form>
<form asp-controller="Microwave" asp-action="Index" method="get">
    <button>Get State</button>
</form>

<p style="background-color:aquamarine">
    Status = @ViewData["State"]
</p>

<p style="background-color:lightsalmon;">
    @ViewData["ErrorMessage"]
</p>

Microwave.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microwave.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>